### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by kpcyrd**
This bumps rand and quickcheck to the latest version. We're about to ship num-bigint with this patch applied.

### CODE REVIEW

**Comment by cuviper** [comment]
The code looks correct. I've also been playing with this locally, and we might want to tweak what `rand` features are pulled in, especially where they're only for dev-deps, but this is a minor point.

However, this is breaking change, since these are public dependencies -- you're changing public trait implementations to semver-incompatible versions.

> We're about to ship num-bigint with this patch applied.

Who is "we"? Are you shipping this as an internal detail, or is it something that will be publicly visible and different than the crates.io `num-bigint`?

**Comment by kpcyrd** [comment]
oops, didn't pay enough attention when writing the text, "we" is referring to the debian rust team, the crate is used when building packages that depend on num-bigint. semver-incompatible reexports aren't much of a problem in that case.

**Comment by programmerjake** [comment]
see also https://github.com/rust-num/num-bigint/issues/75

**Comment by cuviper** [comment]
I took the liberty of rebasing this and stacking some more changes on top. The MSRV is now 1.31, and 128-bit integer support is assumed. MSRV with rand, quickcheck, and no_std are all higher, respectively 1.32, 1.34, and 1.36. We now support rand on no_std too, and I moved some of the rand and quickcheck tests to sub-crates to avoid "polluting" the main dependencies. I want to do a Rust 2018 conversion too, but I'll do that separately.

Thanks!

bors r+

**Comment by cuviper** [comment]
Some 503 errors from crates.io -- let's try again.

bors retry

**Pull request merged**
