### PR TITLE
Add apint to README as another alternative

### PR DESCRIPTION
**Pull request by Robbepop**
The ApInt crate is a pure rust implementation for arbitrary fixed bitwidth modulo arithmetics of integers with a focus on correctness and efficiency - especially for smaller bit widths. It features a generic signless `ApInt` as well as signed counterparts `Int` (signed int) and `UInt` (unsigned int) that are thin wrappers around it. The implementation is unfinished in some parts but that should be fixed over time.

Link to crate at crates.io: https://crates.io/crates/apint
Link to repo at GitHub: https://github.com/robbepop/apint

### CODE REVIEW

**Comment by cuviper** [comment]
Sure, thanks!

bors r+

**Comment by Robbepop** [comment]
I don't understand why bors build (travisCI) failed for this PR. I don't think it is a problem with the PR itself.

**Comment by cuviper** [comment]
Hmm, especially weird since CI already passed the PR initially -- nevermind the fact that you're not even changing the code... let's try again.

bors r+

**Comment by cuviper** [comment]
Meh, I'll just merge this.  But some of those compile times are looking pretty horrible...

**Comment by Robbepop** [comment]
Thanks for merging! :]

**Pull request merged**
