### PR TITLE
Add PartialEq and PartialOrd between built in integer types and BigInt/BigUint

### PR DESCRIPTION
**Pull request by hansihe**
This has been one of the major annoyances for me when using num-bigint compared to something like rug.

### CODE REVIEW

**Comment by cuviper** [comment]
On the surface this seems fine, although I wouldn't include the signed primitives with `BigUint`.

I'm concerned about what this does to type inference though, shown by the changes you had to make to existing tests. I think technically this is a *minor* breaking change according to Rust semver, which is allowable but deserves caution.

I think we'll probably have a semver bump in the near future for rand (#75), so it might be better to wait for that and document this as an upgrade hazard.

**Comment by hansihe** [comment]
I removed the signed integer implementations for BigUint.

**Comment by birkenfeld** [comment]
+1 for this patch.  I was wondering why `Add` etc. are implemented but not the comparison traits.

**Comment by cuviper** [comment]
Included in #136.

**Pull request closed without merging**
