### PR TITLE
Extended the result of to_f32/to_f64 with infinity

### PR DESCRIPTION
**Pull request by notoria**

### CODE REVIEW

**Comment by notoria** [comment]
This PR attempts to solve #161.

**Comment by cuviper** [comment]
Thanks!

bors r+

**Comment by ltratt** [comment]
This isn't a complaint on my part, but this change broke some of our code because we relied on "numbers that are too big to be an f32/f64" returning `None`. I wonder if, perhaps, this might want to be a major release (0.4) rather than a 0.3 point release? FWIW, I think both the original behaviour and the behaviour in this PR are reasonable so I'm not arguing for rolling back the behaviour.

**Comment by cuviper** [comment]
@ltratt Sorry for the trouble! I debated about the change in behavior myself, but I decided that the sign preservation makes this better than `None`. It's already published in 0.3.1, so I don't think we should flip back without a stronger complaint, but I do appreciate your feedback!

**Pull request merged**
