### PR TITLE
Add `DoubleEndedIterator` to `U32Digits` and `U64Digits`

### PR DESCRIPTION
**Pull request by PatrickNorton**
Since `U32Digits` and `U64Digits` do not implement `DoubleEndedIterator`, there is currently no easy way to iterate over the digits in a big-ended fashion.

### CODE REVIEW

**Comment by cuviper** [comment]
> Since `U32Digits` and `U64Digits` do not implement `DoubleEndedIterator`,

Did you explore what it would take to add that implementation instead?

**Comment by PatrickNorton** [comment]
I'd thought about it a little but went with this instead -- doing a quick mockup, it looks like that won't be as difficult as I first thought, so I'll give it a go.

**Comment by PatrickNorton** [comment]
It's definitely a lot cleaner than I expected; I think we should go that route instead.

**Comment by PatrickNorton** [comment]
@cuviper Thoughts on the new implementation?

**Comment by cuviper** [comment]
It looks good to me, thanks!

bors r+

**Comment by cuviper** [comment]
Hmm, that failure with `arbitrary` is not your fault -- I'll see what I can do about this...

**Pull request merged**
