### PR TITLE
Optimize BigUint::modpow for even

### PR DESCRIPTION
**Pull request by youknowone**
~This work is based on #77~

~This version only allow to take `&BigUint` as `exp` argument and doesn't manipulate `exp` not to copy the data of `exp`.~

### CODE REVIEW

**Comment by cuviper** [comment]
While I can appreciate what you're trying to optimize, I think we need not bother -- https://github.com/rust-num/num-bigint/pull/77#issuecomment-488878023

Maybe you'd be interested to try this optimization in `modpow` instead? In that case it's actually reasonable to work with huge exponents.

**Comment by youknowone** [comment]
Thanks for the comment. I will try  `modpow`

**Comment by youknowone** [comment]
@cuviper I replaced the commits to modpow

**Comment by cuviper** [comment]
Sorry for late review. Looks good -- I went ahead and pushed some tweaks of my own to this PR too.

bors r+

**Pull request merged**
